repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: npm-test
        name: npm test
        entry: npm run test:all
        language: system
        pass_filenames: false
        types: [javascript, jsx, ts, tsx]